<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
	  <PublishAot>True</PublishAot>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Swashbuckle.AspNetCore" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\PoC.Core\PoC.Core.csproj" />
	</ItemGroup>

</Project>