<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<OutputType>Exe</OutputType>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<RootNamespace>PoC.Tests</RootNamespace>
		<AssemblyName>PoC.Tests</AssemblyName>

		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
		<TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
	</PropertyGroup>

	<ItemGroup>
		<Using Include="Xunit" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="xunit.v3" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\PoC\PoC.csproj" />
		<ProjectReference Include="..\PoC.Core\PoC.Core.csproj" />
	</ItemGroup>

</Project>